name = "LVModels"
uuid = "c7f46542-cca1-4f5e-96da-3ad09e9393aa"
authors = ["Aditya Sahu <ge27zib@tum.de>"]
version = "1.0.0-DEV"

[compat]
julia = "1.11.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
